version: "3"

tasks:
  lint:
    dir: packages/cms
    cmds:
      - bun x eslint .

  generate:
    preconditions:
      - msg: "This task should be run from the root of the monorepo"
        sh: test -f packages/cms/package.json
      - msg: "This task should be run from the root of the monorepo"
        sh: test -f apps/tinacms/package.json
    sources:
      - packages/tools/src/graphql/**/*
      - packages/cms/**/*
      - apps/tinacms/tina/**/*
      - exclude: packages/cms/src/__generated__/**/*
    generates:
      - packages/cms/src/__generated__/**/*
    cmds:
      - mkdir -p packages/cms/src/__generated__
      - bun x graphql-codegen -p '@w3yz/cms' {{.CLI_ARGS}}
