kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: saleor-media-pvc
  labels:
    app: shared
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
