version: "3"

tasks:
  lint:
    dir: apps/web
    cmds:
      - bun x next lint

  build:
    dir: apps/web
    cmds:
      - bun x next build

  dev:
    dir: apps/web
    cmds:
      - bun x next dev -p 3200

  start:
    dir: apps/web
    cmds:
      - bun x next start
