version: "3"

tasks:
  lint:
    dir: apps/web
    cmds:
      - bun -b x next lint

  build:
    dir: apps/web
    cmds:
      - bun -b x next build

  dev:
    dir: apps/web
    env:
      NODE_ENV: "development"
      TINA_PUBLIC_IS_LOCAL: true,
      NEXT_PUBLIC_URL: "http://localhost:3000"
      NEXT_PUBLIC_SALEOR_API_URL: "https://dev-shop-api.w3yz.dev/graphql/"
      NEXT_PUBLIC_STOREFRONT_URL: "http://localhost:3000"
      NEXTAUTH_SECRET: "changeme"
    cmds:
      - bun -b x next dev

  start:
    dir: apps/web
    cmds:
      - bun -b x next start
