apiVersion: skaffold/v4beta10
kind: Config

profiles:
  - name: 01-saleor
    manifests:
      hooks:
        before:
          - host:
              command: ["./generate-ghcr-secret.sh"]
              dir: .
          - host:
              command:
                ["deno", "run", "-A", "./generate-01-saleor-shop-config.ts"]
              dir: .

      kustomize:
        paths: ["./gen"]
