apiVersion: skaffold/v4beta10
kind: Config

manifests:
  hooks:
    before:
      - host:
          command: ["deno", "task", "-q", "t", "generate"]
          dir: ./tooling

profiles:
  - name: shop
    manifests:
      kustomize:
        paths:
          - ./shop/kustomize/shop/current
