apiVersion: skaffold/v4beta10
kind: Config

requires:
  - path: ./ops/steps/01-saleor
  - path: ./ops/steps/02-storefront-build
  - path: ./ops/steps/03-storefront-deploy

profiles:
  - name: 01-saleor
