apiVersion: skaffold/v4beta10
kind: Config

build:
  artifacts:
    - image: w3yz-devbox
      context: .
      sync:
        manual:
          - src: "."
            dest: "/code"
            strip: "node_modules"

manifests:
  hooks:
    before:
      - host:
          command: ["deno", "task", "-q", "t", "generate"]
          dir: ./tooling

profiles:
  - name: shop
    manifests:
      kustomize:
        paths:
          - ./shop/kustomize/shop/current
