apiVersion: skaffold/v4beta10
kind: Config

manifests:
  hooks:
    before:
      - host:
          command: ["t", "generate", "$SHOP_NAME"]
          dir: .

requires:
  - path: ./apps/web

profiles:
  - name: dev
    manifests:
      kustomize:
        paths:
          - ./shop/kustomize/shop/current
