apiVersion: skaffold/v4beta10
kind: Config

metadata:
  name: w3yz

manifests:
  rawYaml:
    - ./ops/main/namespace.yaml
    - ./ops/main/w3yz-supabase-namespace.yaml
  hooks:
    before:
      - host:
          command: ["deno", "run", "-A", "./generate-kustomize.ts"]
          dir: ./ops/kustomize-generation
  helm:
    releases:
      - name: supabase
        remoteChart: oci://registry-1.docker.io/bitnamicharts/supabase
        createNamespace: true
        recreatePods: true
        skipBuildDependencies: false
        useHelmSecrets: false
        wait: false
        namespace: w3yz-supabase
        setValues:
          global.storageClass: "longhorn"
          namespaceOverride: "w3yz-supabase"
  kustomize:
    paths: ["./ops/gen"]

profiles:
  - name: release
    build:
      hooks:
        before:
          - command: ["task", "build", "-f"]
            dir: .
      artifacts:
        - image: ghcr.io/w3yz-phoenix/w3yz
          context: ./fast-build
          docker:
            dockerfile: ./fast-build/Dockerfile
            buildArgs:
              NEXT_PUBLIC_ROOT_DOMAIN: "{{.NEXT_PUBLIC_ROOT_DOMAIN}}"
              NEXT_PUBLIC_SHOP_NAME: "{{.NEXT_PUBLIC_SHOP_NAME}}"
              NEXT_PUBLIC_MONGO_PORT: "{{.NEXT_PUBLIC_MONGO_PORT}}"
              MY_PERSONAL_GITHUB_TOKEN: "{{.MY_PERSONAL_GITHUB_TOKEN}}"
      tagPolicy:
        sha256: {}
    manifests:
      hooks:
        before:
          - host:
              command:
                [
                  "deno",
                  "run",
                  "-A",
                  "./generate-kustomize.ts",
                  "-p",
                  "release",
                ]
              dir: ./ops/kustomize-generation
      kustomize:
        paths: ["./ops/gen"]
