version: "3"

vars:
  APP_PATH: "{{ .USER_WORKING_DIR }}"
  OUT_PATH: "{{.USER_WORKING_DIR}}/dist"

tasks:
  default:
    dir: "{{.APP_PATH}}"

  install:
    cmds:
      - bun install

  build-apps:
    deps: [install]
    cmds:
      - bun --bun "--filter=@w3yz-app/*" run build

  build:
    deps: [build-apps]
    cmds:
      - rm -rf "{{.OUT_PATH}}"/
      - |
        rsync -avm \
          --include='*/' \
          --include='package.json' \
          --include='apps/**/.next/**' \
          --include='apps/**/package.json' \
          --include='apps/**/public/**' \
          --exclude='**/node_modules/**' \
          --exclude='**/dist/**' \
          --exclude='*' \
          . "{{.OUT_PATH}}"
