version: "3"

interval: 500ms

# env:
#   NEXT_PUBLIC_ECOM_API_URL: "https://dev-shop-api.w3yz.dev/graphql/"
#   NEXT_PUBLIC_ECOM_NAME: "furniture"
#   NEXT_PUBLIC_CMS_BASE_URL: "http://localhost:3000"
#   NEXTAUTH_SECRET: "changeme"

includes:
  ecom:
    taskfile: ./packages/ecom/Taskfile.yml
  cms:
    taskfile: ./packages/cms/Taskfile.yml
  storefront:
    taskfile: ./apps/storefront/Taskfile.yml
  tinacms:
    taskfile: ./apps/tinacms/Taskfile.yml

tasks:
  install:
    cmds:
      - bun install

  generate:
    deps: [ecom:generate, cms:generate]

  watch:
    watch: true
    deps: [generate]

  build:
    preconditions:
      - bun version
      - msg: "Please run this command in the root directory of the project"
        sh: "test -f ./Taskfile.yml && test -f ./package.json"
    requires:
      vars:
        - "ROOT_DOMAIN"
        - "SHOP_NAME"
        - "MONGO_PORT"
        - "MY_PERSONAL_GITHUB_TOKEN"
    vars:
      NODE_ENV: production
      SHOP_DOMAIN: "{{.SHOP_NAME}}.{{.ROOT_DOMAIN}}"
      NEXT_PUBLIC_URL: "https://{{.SHOP_NAME}}.{{.ROOT_DOMAIN}}"
      NEXT_PUBLIC_ECOM_API_URL: "https://api.{{.SHOP_NAME}}.{{.ROOT_DOMAIN}}/graphql/"
      NEXT_PUBLIC_ECOM_NAME: "{{.SHOP_NAME}}"
      NEXT_PUBLIC_CMS_BASE_URL: "https://{{.SHOP_NAME}}.{{.ROOT_DOMAIN}}"
      NEXTAUTH_SECRET: "change-me"
      MONGODB_URI: "mongodb://{{.SHOP_DOMAIN}}:{{.MONGO_PORT}}/{{.SHOP_NAME}}"
      GITHUB_OWNER: w3yz-phoenix
      GITHUB_REPO: live
      GITHUB_BRANCH: main
      GITHUB_PERSONAL_ACCESS_TOKEN: "{{.MY_PERSONAL_GITHUB_TOKEN}}"
      TINA_PUBLIC_IS_LOCAL: "false"
      NEXT_PUBLIC_TINA_IS_LOCAL: "false"
    env:
      ROOT_DOMAIN: "{{.ROOT_DOMAIN}}"
      SHOP_NAME: "{{.SHOP_NAME}}"
      MONGO_PORT: "{{.MONGO_PORT}}"
      MY_PERSONAL_GITHUB_TOKEN: "{{.MY_PERSONAL_GITHUB_TOKEN}}"
      NODE_ENV: "{{.NODE_ENV}}"
      SHOP_DOMAIN: "{{.SHOP_DOMAIN}}"
      NEXT_PUBLIC_URL: "{{.NEXT_PUBLIC_URL}}"
      NEXT_PUBLIC_ECOM_API_URL: "{{.NEXT_PUBLIC_ECOM_API_URL}}"
      NEXT_PUBLIC_ECOM_NAME: "{{.NEXT_PUBLIC_ECOM_NAME}}"
      NEXT_PUBLIC_CMS_BASE_URL: "{{.NEXT_PUBLIC_CMS_BASE_URL}}"
      NEXT_PUBLIC_SHOP_DOMAIN: "{{.SHOP_NAME}}.{{.ROOT_DOMAIN}}"
      NEXTAUTH_SECRET: "{{.NEXTAUTH_SECRET}}"
      MONGODB_URI: "{{.MONGODB_URI}}"
      GITHUB_OWNER: "{{.GITHUB_OWNER}}"
      GITHUB_REPO: "{{.GITHUB_REPO}}"
      GITHUB_BRANCH: "{{.GITHUB_BRANCH}}"
      GITHUB_PERSONAL_ACCESS_TOKEN: "{{.GITHUB_PERSONAL_ACCESS_TOKEN}}"
      TINA_PUBLIC_IS_LOCAL: "{{.TINA_PUBLIC_IS_LOCAL}}"
      NEXT_PUBLIC_TINA_IS_LOCAL: "{{.NEXT_PUBLIC_TINA_IS_LOCAL}}"
    cmds:
      - bun install
      - task ecom:generate -f
      - task tinacms:build -f
      - task cms:generate -f
      # - task storefront:build -f
      - rm -rf ./fast-build/dist/
      - rm -rf ./fast-build/dist.tgz

      - mkdir -p ./fast-build/dist/storefront
      - cp -R apps/storefront/.next ./fast-build/dist/storefront
      - cp -R apps/tinacms/public ./fast-build/dist/storefront
      - cp -R apps/storefront/package.json ./fast-build/dist/storefront

      - mkdir -p ./fast-build/dist/tinacms
      - cp -R apps/tinacms/.next ./fast-build/dist/tinacms
      - cp -R apps/tinacms/public ./fast-build/dist/tinacms
      - cp -R apps/tinacms/content ./fast-build/dist/tinacms
      - cp -R apps/tinacms/package.json ./fast-build/dist/tinacms

      - rm -rf node_modules
      - bun install --production
      - mv node_modules ./fast-build/dist/node_modules

      - cd ./fast-build && tar czf ./dist.tgz ./dist && cd ..
      - rm -rf ./fast-build/dist

      - cd ..
      - rm -rf node_modules

  dev:
    deps: [storefront:dev, tinacms:dev]

  dev:prod:
    deps: [storefront:dev:prod, tinacms:dev:prod]

  deploy-debug:
    env:
      SHOP_NAME: puledro
    cmds:
      - kubectl -n w3yz-shop-$SHOP_NAME delete deployment storefront || true
      - MY_PERSONAL_GITHUB_TOKEN=(gh auth token) skaffold render -p shop | kubectl apply -f -

  deploy:
    requires:
      vars:
        - "SHOP_NAME"
    cmds:
      - MY_PERSONAL_GITHUB_TOKEN=(gh auth token) skaffold render -p shop | kubectl apply -f -
