version: "3"

interval: 500ms

includes:
  ui-core:
    taskfile: ./packages/ui-core/Taskfile.yml
    dir: ./packages/ui-core
  storefront:
    taskfile: ./apps/storefront/Taskfile.yml
    dir: ./apps/storefront
  gql-tina:
    taskfile: ./packages/gql-tina/Taskfile.yml
  gql-saleor:
    taskfile: ./packages/gql-saleor/Taskfile.yml

tasks:
  install:
    cmds:
      - bun install

  build-apps:
    cmds:
      - bun --bun "--filter=@w3yz-app/*" run build

  build:
    deps: [build-apps]
    cmds:
      - rm -rf ./dist && mkdir -p ./dist
      - |
        rsync -avm --include='*/' \
          --include='*/.next/***' \
          --include='*/public/***' \
          --include='*/package.json' \
          --exclude='*' \
          apps/ dist/

  fetch-schema:
    vars:
      SALEOR_SCHEMA_VERSION: "3.19"
    cmds:
      - rm -rf packages/ecom-saleor/src/vendor;
      - mkdir -p packages/ecom-saleor/src/vendor;
      - curl -L https://raw.githubusercontent.com/saleor/saleor/{{.SALEOR_SCHEMA_VERSION}}/saleor/graphql/schema.graphql -o packages/ecom-saleor/src/vendor/saleor.graphql

  generate:
    deps: [gql-tina:generate, gql-saleor:generate]

  watch:
    watch: true
    deps: [generate]

  dev:
    cmds:
      - task: storefront:dev
