version: "3"

interval: 500ms

env:
  NEXT_PUBLIC_ECOM_API_URL: "https://dev-shop-api.w3yz.dev/graphql/"
  NEXT_PUBLIC_ECOM_NAME: "furniture"
  NEXT_PUBLIC_CMS_BASE_URL: "http://localhost:3000"
  NEXTAUTH_SECRET: "changeme"

includes:
  ecom:
    taskfile: ./packages/ecom/Taskfile.yml
  cms:
    taskfile: ./packages/cms/Taskfile.yml
  web:
    taskfile: ./apps/web/Taskfile.yml
  tinacms:
    taskfile: ./apps/tinacms/Taskfile.yml

tasks:
  install:
    cmds:
      - bun install

  generate:
    deps: [install, ecom:generate, cms:generate]

  watch:
    watch: true
    deps: [generate]

  build:
    deps: [generate, tinacms:build, web:build, generate]

  dev:
    deps: [install, web:dev, tinacms:dev]

  dev:prod:
    deps: [install, web:dev:prod, tinacms:dev:prod]
