version: "3"

tasks:
  install:
    cmds:
      - bun install

  build-apps:
    deps: [install]
    cmds:
      - bun --bun "--filter=@w3yz-app/*" run build

  build:
    # deps: [build-apps]
    cmds:
      - rm -rf dist/
      - |
        rsync -avm \
          --include='*/' \
          --include='package.json' \
          --include='apps/**/.next/**' \
          --include='apps/**/package.json' \
          --include='apps/**/public/**' \
          --exclude='**/node_modules/**' \
          --exclude='**/dist/**' \
          --exclude='*' \
          . ./dist
