version: "3"

tasks:
  install:
    cmds:
      - bun install

  build-apps:
    cmds:
      - bun --bun "--filter=@w3yz-app/*" run build

  build:
    deps: [build-apps]
    cmds:
      - rm -rf ./dist && mkdir -p ./dist
      - |
        rsync -avm --include='*/' \
          --include='*/.next/***' \
          --include='*/public/***' \
          --include='*/package.json' \
          --exclude='*' \
          apps/ dist/

  fetch-schema:
    vars:
      SALEOR_SCHEMA_VERSION: "3.19"
    cmds:
      - rm -rf packages/ecom-saleor/src/vendor;
      - mkdir -p packages/ecom-saleor/src/vendor;
      - curl -L https://raw.githubusercontent.com/saleor/saleor/{{.SALEOR_SCHEMA_VERSION}}/saleor/graphql/schema.graphql -o packages/ecom-saleor/src/vendor/saleor.graphql

  generate-tina:
    sources:
      - apps/storefront/config/**/*.ts
      - apps/storefront/content/**/*
      - apps/storefront/tina/**/*
      - apps/storefront/public/**/*
      - packages/core/**/*.tsx
      - packages/core/**/*.ts
      - packages/cms-tina/**/*
      - exclude: packages/cms-tina/node_modules/**/*
      - exclude: packages/cms-tina/src/generated/**/*
    generates:
      - packages/cms-tina/src/generated/tinacms.gen.ts
    cmd: bun -b x graphql-codegen -p '@w3yz/cms-tina'

  generate-saleor:
    sources:
      - packages/ecom-saleor/**/*
      - exclude: packages/ecom-saleor/node_modules/**/*
      - exclude: packages/ecom-saleor/src/generated/**/*.ts
    generates:
      - packages/ecom-saleor/src/generated/**/*.ts
    cmd: bun -b x graphql-codegen -p '@w3yz/ecom-saleor'

  generate:
    deps: [generate-tina, generate-saleor]

  storefront:
    run: once
    cmds:
      - bun -b "--filter=@w3yz-app/storefront" run dev

  watch:
    watch: true
    deps: [generate]

  dev:
    deps: [storefront]
