version: "3"

tasks:
  install:
    cmds:
      - bun install

  build-apps:
    cmds:
      - bun --bun "--filter=@w3yz-app/*" run build

  build:
    deps: [build-apps]
    cmds:
      - rm -rf ./dist && mkdir -p ./dist
      - |
        rsync -avm --include='*/' \
          --include='*/.next/***' \
          --include='*/public/***' \
          --include='*/package.json' \
          --exclude='*' \
          apps/ dist/

  dev:
    cmds:
      - bun --bun "--filter=@w3yz-app/*" run dev
