version: "3"

interval: 500ms

env:
  NEXT_PUBLIC_ECOM_API_URL: "https://dev-shop-api.w3yz.dev/graphql/"
  NEXT_PUBLIC_ECOM_NAME: "furniture"
  NEXT_PUBLIC_CMS_BASE_URL: "http://localhost:3000"
  NEXTAUTH_SECRET: "changeme"

includes:
  ecom:
    taskfile: ./packages/ecom/Taskfile.yml
  cms:
    taskfile: ./packages/cms/Taskfile.yml
  storefront:
    taskfile: ./apps/storefront/Taskfile.yml
  tinacms:
    taskfile: ./apps/tinacms/Taskfile.yml

tasks:
  install:
    cmds:
      - bun install

  generate:
    deps: [ecom:generate, cms:generate]

  watch:
    watch: true
    deps: [generate]

  build-apps:
    cmds:
      - bun "--filter=@w3yz-app/tinacms" run build
      - task: generate
      - bun "--filter=@w3yz-app/tinacms" run start
      - bun "--filter=@w3yz-app/storeferont" run build

  build:
    deps: [build-apps]
    cmds:
      - rm -rf ./dist && mkdir -p ./dist
      - |
        rsync -avm --include='*/' \
          --include='*/.next/***' \
          --include='*/public/***' \
          --include='*/package.json' \
          --exclude='*' \
          apps/ dist/

  dev:
    deps: [storefront:dev, tinacms:dev]

  dev:prod:
    deps: [storefront:dev:prod, tinacms:dev:prod]

  deploy-debug:
    env:
      SHOP_NAME: puledro
    cmds:
      - kubectl -n w3yz-shop-$SHOP_NAME delete deployment storefront || true
      - GITHUB_TOKEN=(gh auth token) skaffold render -p shop | kubectl apply -f -

  deploy:
    requires:
      vars:
        - "SHOP_NAME"
    cmds:
      - GITHUB_TOKEN=(gh auth token) skaffold render -p shop | kubectl apply -f -
