version: "3"

# vars:
#   APP_PATH: "{{ .USER_WORKING_DIR }}"
#   OUT_PATH: "{{.USER_WORKING_DIR}}/dist"

tasks:
  default:
    dir: "{{.APP_PATH}}"

  install:
    cmds:
      - bun install

  build-apps:
    deps: [install]
    cmds:
      - bun --bun "--filter=@w3yz-app/*" run build

  build:
    # deps: [build-apps]
    vars:
      APP_PATH: "{{.USER_WORKING_DIR}}"
      OUT_PATH: "{{.USER_WORKING_DIR}}/dist"
    requires:
      vars: [APP_PATH, OUT_PATH]
    cmds:
      - rm -rf "{{.OUT_PATH}}"
      - |
        rsync -avm \
          --include='*/' \
          --include='**/package.json' \
          --include='**/.next' \
          --include='**/public' \
          --exclude='*' \
          {{.APP_PATH}} "{{.OUT_PATH}}"
