version: "3"

dotenv: [".env", "{{.ENV}}/.env.", "{{.HOME}}/.env"]

interval: 500ms

includes:
  ecom:
    taskfile: ./packages/ecom/Taskfile.yaml
  cms:
    taskfile: ./packages/cms/Taskfile.yaml
  storefront:
    taskfile: ./apps/storefront/Taskfile.yaml
  tinacms:
    taskfile: ./apps/tinacms/Taskfile.yaml
  ops:
    taskfile: ./ops/Taskfile.yaml
    dir: ./ops
  dashboard:
    taskfile: ./apps/dashboard/Taskfile.yaml
    dir: ./apps/dashboard
  dev:
    taskfile: ./ops/dev.Taskfile.yaml
    dir: .

tasks:
  install:
    cmds:
      - bun install

  generate:
    deps: [ecom:generate, cms:generate]

  watch:
    watch: true
    deps: [dev:generate-dev-env, generate]

  build:
    preconditions:
      - bun version
    requires:
      vars:
        - "NEXT_PUBLIC_ROOT_DOMAIN"
        - "NEXT_PUBLIC_SHOP_NAME"
        - "NODE_ENV"
    env:
      NEXT_PUBLIC_ROOT_DOMAIN: "{{.NEXT_PUBLIC_ROOT_DOMAIN}}"
      NEXT_PUBLIC_SHOP_NAME: "{{.NEXT_PUBLIC_SHOP_NAME}}"
      NODE_ENV: "{{.NODE_ENV}}"
    deps: [dev:generate-prod-env]
    cmds:
      - source .env
      - bun install
      - task ecom:generate -f
      - task tinacms:build -f
      - task cms:generate -f
      - task storefront:build -f
      - rm -rf ./fast-build/dist/
      - rm -rf ./fast-build/dist.tgz

      - mkdir -p ./fast-build/dist/storefront
      - cp -R apps/storefront/.next ./fast-build/dist/storefront
      - cp -R apps/tinacms/public ./fast-build/dist/storefront
      - cp -R apps/storefront/package.json ./fast-build/dist/storefront

      - mkdir -p ./fast-build/dist/tinacms
      - cp -R apps/tinacms/.next ./fast-build/dist/tinacms
      - cp -R apps/tinacms/public ./fast-build/dist/tinacms
      - cp -R apps/tinacms/content ./fast-build/dist/tinacms
      - cp -R apps/tinacms/package.json ./fast-build/dist/tinacms

      - rm -rf node_modules
      - bun install --production
      - mv node_modules ./fast-build/dist/node_modules

      - cd ./fast-build && tar czf ./dist.tgz ./dist && cd ..
      - rm -rf ./fast-build/dist

      - cd ..
      - rm -rf node_modules

  dev:
    deps: [storefront:dev, tinacms:dev]

  storefront-dev:prod:
    deps: [dev:generate-almost-prod-like-env, storefront:dev:prod]

  tinacms-dev:prod:
    deps: [dev:generate-almost-prod-like-env, tinacms:dev:prod]

  dev:prod:
    deps: [storefront-dev:prod, tinacms-dev:prod]

  render:
    cmds:
      - rm -rf .env
      - SHOP_NAME=${SHOP_NAME} task dev:generate-prod-env -f
      - source .env
      - task ops:render -f

  deploy:
    requires:
      vars:
        - "SHOP_NAME_OVERRIDE"
    env:
      SHOP_NAME_OVERRIDE: "{{.SHOP_NAME_OVERRIDE}}"
      ROOT_NAME_OVERRIDE: "beta.w3yz.dev"
    cmds:
      - rm -rf .env
      - task dev:generate-prod-env -f
      - source .env
      - task ops:deploy -f
