version: "3"

interval: 500ms

env:
  NODE_ENV: "development"
  TINA_PUBLIC_IS_LOCAL: true,
  NEXT_PUBLIC_URL: "http://localhost:3000"
  NEXT_PUBLIC_ECOM_API_URL: "https://dev-shop-api.w3yz.dev/graphql/"
  NEXT_PUBLIC_ECOM_NAME: "furniture"
  NEXT_PUBLIC_ECOM_URL: "http://localhost:3000"
  NEXT_PUBLIC_CMS_API_URL: "http://localhost:3000/api/tina/gql"
  NEXTAUTH_SECRET: "changeme"

includes:
  ecom:
    taskfile: ./packages/ecom/Taskfile.yml
  cms:
    taskfile: ./packages/cms/Taskfile.yml
  web:
    taskfile: ./apps/web/Taskfile.yml

tasks:
  install:
    cmds:
      - bun install

  generate:
    deps: [install, ecom:generate, cms:generate]

  watch:
    watch: true
    deps: [generate]

  dev:
    deps: [install, web:dev, cms:dev]
