version: "3"

interval: 500ms

includes:
  ecom:
    taskfile: ./packages/ecom/Taskfile.yml
  cms:
    taskfile: ./packages/cms/Taskfile.yml
  web:
    taskfile: ./apps/web/Taskfile.yml

tasks:
  install:
    cmds:
      - bun install

  generate:
    deps: [ecom:generate, cms:generate]

  watch:
    watch: true
    deps: [generate]

  dev:
    deps: [web:dev, cms:dev]
