import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { FurnitureProvider } from "@w3yz/core/export/ui/furniture/provider";
import { Header } from "@w3yz/core/export/ui/furniture/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <FurnitureProvider>
          <Header />
          {children}
        </FurnitureProvider>
      </body>
    </html>
  );
}
