import "../shadcn.css";
import { Inter } from "next/font/google";
import { Button } from "@@shadcn/components/button";

import type { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center justify-between p-24">
          <Button variant="destructive">aaa</Button>
          {children}
        </main>
      </body>
    </html>
  );
}
