services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  graphql:
    image: node:alpine
    command: npx pgl@beta -P pgl/amber -e -c 'postgres://postgres:postgres@postgres:5432/postgres'
    ports:
      - 5678:5678
    depends_on:
      - postgres

volumes:
  postgres-data:
