apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
    component: saleor
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
        - name: init-postgres
          image: alpine
          user: root
          command:
            - /bin/sh
            - -c
            - |
              echo "Generate init sql files"

              apk add --no-cache curl vim

              curl https://gist.githubusercontent.com/yasinuslu/753779df923b1ff70134abcd78ab99bf/raw/38b411b8a982fd12a6c963c874b2aa5fc637d438/gistfile1.txt -o /tmp/saleor-dump.sql

              # replace API_FQDN with $API_FQDN
              sed -i "s/API_FQDN/$API_FQDN/g" /tmp/saleor-dump.sql

              cp -f /tmp/saleor-dump.sql /tmp-init-db/02-init-saleor-db.sql
          env:
            - name: API_FQDN
              valueFrom:
                configMapKeyRef:
                  name: shop-config
                  key: API_FQDN
          volumeMounts:
            - name: tmp-init-db
              mountPath: /tmp-init-db
      containers:
        - name: postgres
          image: postgres:alpine
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-pv-storage
              mountPath: /var/lib/postgresql/data
            - name: tmp-init-db
              mountPath: /docker-entrypoint-initdb.d/02-init-saleor-db.sql
              subPath: 02-init-saleor-db.sql
              readOnly: true
            - name: init-db
              mountPath: /docker-entrypoint-initdb.d/01-init-databases.sh
              subPath: 01-init-databases.sh
              readOnly: true
      volumes:
        - name: postgres-pv-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: tmp-init-db
          emptyDir: {}
        - name: init-db
          configMap:
            name: postgres-init-db
