apiVersion: v1
kind: Service
metadata:
  name: ferretdb
  labels:
    app: ferretdb
spec:
  type: ClusterIP
  selector:
    app: ferretdb
  ports:
    - port: 27017
      targetPort: 27017
      name: db
    - port: 8080
      targetPort: 8080
      name: http
