apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: storefront-scripts
    files:
      - start-storefront.sh
      - start-tinacms.sh
