apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          args:
            - celery
            - -A
            - saleor
            - --app=saleor.celeryconf:app
            - worker
            - --loglevel=info
            - -B
          image: ghcr.io/saleor/saleor:3.19
          resources:
            limits:
              cpu: "1"
              memory: "500Mi"
            requests:
              cpu: "0.5"
              memory: "200Mi"
          ports:
            - containerPort: 8000
              name: worker
          volumeMounts:
            - name: worker-pv
              mountPath: /app/media
      volumes:
        - name: worker-pv
          persistentVolumeClaim:
            claimName: saleor-media-pvc
