apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

secretGenerator:
  - name: saleor-secret
    literals:
      - POSTGRES_DB=saleor
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor
      - SECRET_KEY=secret

patches:
  - patch: |-
      - op: add
        path: /metadata/annotations
        value:
          kubernetes.io/ingress.class: "nginx"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      - op: replace
        path: /spec/ingressClassName
        value: "nginx"
    target:
      kind: Ingress
      labelSelector: component=saleor

  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value:
          - configMapRef:
              name: saleor-config
          - secretRef:
              name: saleor-secret
    target:
      kind: Deployment
      labelSelector: component=saleor

  - patch: |-
      - op: add
        path: /spec/template/spec/initContainers/0/envFrom
        value:
          - configMapRef:
              name: saleor-config
          - secretRef:
              name: saleor-secret
    target:
      kind: Deployment
      name: api

replacements:
  - source:
      kind: ConfigMap
      name: shop-config
      fieldPath: data.API_FQDN
    targets:
      - select:
          kind: Ingress
          name: api-ingress
        fieldPaths:
          - spec.tls.0.hosts.0
          - spec.rules.0.host
  - source:
      kind: ConfigMap
      name: shop-config
      fieldPath: data.DASHBOARD_FQDN
    targets:
      - select:
          kind: Ingress
          name: dashboard-ingress
        fieldPaths:
          - spec.tls.0.hosts.0
          - spec.rules.0.host
