version: "3"

tasks:
  generate:
    sources:
      - apps/storefront/tina/**/*
      - packages/gql-tina/**/*
      - exclude: packages/gql-tina/src/__generated__/**/*
    generates:
      - packages/gql-tina/src/__generated__/**/*
    cmds:
      - mkdir -p packages/gql-tina/src/__generated__
      - bun -b x graphql-codegen -p '@w3yz/gql-tina' {{.CLI_ARGS}}
