apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          args:
            - celery
            - -A
            - saleor
            - --app=saleor.celeryconf:app
            - worker
            - --loglevel=info
            - -B
          image: ghcr.io/saleor/saleor:3.19
          env:
            - name: ALLOWED_CLIENT_HOSTS
              value: "*"
            - name: ALLOWED_HOSTS
              value: "*"

          ports:
            - containerPort: 8000
              name: worker
          volumeMounts:
            - name: worker-pv
              mountPath: /app/media
      volumes:
        - name: worker-pv
          persistentVolumeClaim:
            claimName: saleor-media-pvc
