version: "3"

env:
  LIMACTL_INSTANCE: default
  LIMA_INSTANCE: default

tasks:
  ssh:
    cmds:
      - ssh -F $HOME/.lima/default/ssh.config lima-default

  init:
    cmds:
      - limactl delete default --force || true
      - |
        limactl start \
          --tty=false \
          --name=default \
          --cpus=4 \
          --memory=8 \
          # --vm-type=vz \
          # --mount-type=virtiofs \
          --mount-writable \
          template://ubuntu
      - limactl --tty=false shell default bash -c "./scripts/lima-init.sh"

  print:
    cmds:
      - skaffold -v trace render -p shop-baseline {{.CLI_ARGS}} | code -

  undeploy:
    requires:
      vars:
        - "SHOP_NAME"
    env:
      NEXT_PUBLIC_SHOP_NAME: "{{.SHOP_NAME}}"
    dir: ../
    cmd: |
      kubectl delete namespace w3yz-shop-$NEXT_PUBLIC_SHOP_NAME || true;

  render:
    requires:
      vars:
        - "SHOP_NAME"
        - "MY_PERSONAL_GITHUB_TOKEN"
        - "NAMESPACE"
    env:
      SHOP_NAME: "{{.SHOP_NAME}}"
      NEXT_PUBLIC_SHOP_NAME: "{{.SHOP_NAME}}"
      MY_PERSONAL_GITHUB_TOKEN: "{{.MY_PERSONAL_GITHUB_TOKEN}}"
      NAMESPACE: "{{.NAMESPACE}}"
    dir: ../
    cmd: |
      skaffold render -i ghcr.io/w3yz-phoenix/w3yz:main -p release

  deploy:
    requires:
      vars:
        - "SHOP_NAME"
        - "MY_PERSONAL_GITHUB_TOKEN"
        - "NAMESPACE"
    env:
      SHOP_NAME: "{{.SHOP_NAME}}"
      NEXT_PUBLIC_SHOP_NAME: "{{.SHOP_NAME}}"
      MY_PERSONAL_GITHUB_TOKEN: "{{.MY_PERSONAL_GITHUB_TOKEN}}"
      NAMESPACE: "{{.NAMESPACE}}"
    dir: ../
    cmd: |
      skaffold deploy -i ghcr.io/w3yz-phoenix/w3yz:main -p release;

  run:
    cmds:
      - skaffold run -p shop-baseline
