version: "3"

env:
  LIMACTL_INSTANCE: default
  LIMA_INSTANCE: default

tasks:
  ssh:
    cmds:
      - ssh -F $HOME/.lima/default/ssh.config lima-default

  init:
    cmds:
      - limactl delete default --force || true
      - |
        limactl start \
          --tty=false \
          --name=default \
          --cpus=4 \
          --memory=8 \
          # --vm-type=vz \
          # --mount-type=virtiofs \
          --mount-writable \
          template://ubuntu
      - limactl --tty=false shell default bash -c "./scripts/lima-init.sh"

  print:
    cmds:
      - skaffold -v trace render -p shop-baseline {{.CLI_ARGS}} | code -

  undeploy:
    requires:
      vars:
        - "NEXT_PUBLIC_SHOP_NAME"
    env:
      NEXT_PUBLIC_SHOP_NAME: "{{.NEXT_PUBLIC_SHOP_NAME}}"
    dir: ../
    cmd: |
      kubectl delete namespace w3yz-shop-$NEXT_PUBLIC_SHOP_NAME || true;

  render:
    requires:
      vars:
        - "NEXT_PUBLIC_SHOP_NAME"
    env:
      NEXT_PUBLIC_SHOP_NAME: "{{.NEXT_PUBLIC_SHOP_NAME}}"
    dir: ../
    cmd: |
      export MY_PERSONAL_GITHUB_TOKEN="$(gh auth token)";
      export NEXT_PUBLIC_ROOT_DOMAIN="beta.w3yz.dev";
      export NAMESPACE="w3yz-shop-$NEXT_PUBLIC_SHOP_NAME";

      export NEXT_PUBLIC_MONGO_PORT="$(kubectl get -n w3yz-shop-$NEXT_PUBLIC_SHOP_NAME service ferretdb-exposed -o json | jq '.spec.ports[0].nodePort' || echo 27017)";

      skaffold render -i ghcr.io/w3yz-phoenix/w3yz:main -p release

  deploy:
    requires:
      vars:
        - "NEXT_PUBLIC_SHOP_NAME"
    env:
      NEXT_PUBLIC_SHOP_NAME: "{{.NEXT_PUBLIC_SHOP_NAME}}"
    dir: ../
    cmd: |
      export MY_PERSONAL_GITHUB_TOKEN="$(gh auth token)";
      export NEXT_PUBLIC_ROOT_DOMAIN="beta.w3yz.dev";
      export NAMESPACE="w3yz-shop-$NEXT_PUBLIC_SHOP_NAME";

      docker login https://ghcr.io -u yasinuslu -p "$MY_PERSONAL_GITHUB_TOKEN" || true;
      kubectl -n "$NAMESPACE" create secret docker-registry ghcr-secret --docker-server=https://ghcr.io --docker-username=yasinuslu --docker-password="$MY_PERSONAL_GITHUB_TOKEN" --docker-email="nepjua@gmail.com" || true;

      export NAMESPACE_EXISTS="$(kubectl get namespace $NAMESPACE 2> /dev/null)";
      if [ -z "$NAMESPACE_EXISTS" ]; then
        echo "Namespace does not exist, provisioning..."
        skaffold run -p provision || true;
      else
        echo "Namespace already exists running update..."
        docker login https://ghcr.io -u yasinuslu -p "$MY_PERSONAL_GITHUB_TOKEN" || true;
        kubectl -n "$NAMESPACE" create secret docker-registry ghcr-secret --docker-server=https://ghcr.io --docker-username=yasinuslu --docker-password="$MY_PERSONAL_GITHUB_TOKEN" --docker-email="nepjua@gmail.com" || true;
        export NEXT_PUBLIC_MONGO_PORT="$(kubectl get -n w3yz-shop-$NEXT_PUBLIC_SHOP_NAME service ferretdb-exposed -o json | jq '.spec.ports[0].nodePort' || echo 27017)";
        skaffold deploy -i ghcr.io/w3yz-phoenix/w3yz:main -p release || true;
      fi;

  run:
    cmds:
      - skaffold run -p shop-baseline
