version: "3"

tasks:
  lint:
    cmds:
      - bun x eslint .

  build-tina:
    cmds:
      - bun -b x tinacms build

  build-next:
    cmds:
      - bun -b x next build

  build:
    deps: [build-tina, build-next]

  dev:
    env:
      NODE_ENV: "development"
      TINA_PUBLIC_IS_LOCAL: true
      NEXT_PUBLIC_SALEOR_API_URL: "https://dev-shop-api.w3yz.dev/graphql/"
      NEXT_PUBLIC_STOREFRONT_URL: "http://localhost:3000"
      NEXTAUTH_SECRET: "changeme"
    cmds:
      - bun -b x tinacms dev -c "bun -b x next dev"

  start:
    cmds:
      - bun -b x next start

  add-component:
    cmds:
      - bun -b x shadcn-ui@latest add -p ../../packages/ui-shadcn/src/components/ui/ -o -y {{.CLI_ARGS}}
